#define PORT 6969
#define BUFFER_SIZE 516
#define SERVER_IP 127.0.0.1
#define BLOCK_SIZE 512
#define RRQ 1
#define WRQ 2
#define DATA 3
#define ACK 4
#define ERROR 5



enum ERR_MSGS{UNDEFINED, FILENOTFOUND, ACCESSVIOLATION, DISKFULL, ILLEGALOP, UNKNOWNTID, FILEPRESENT, NOSUCHUSER};
